### ISSUE TITLE
Build (linker) failure on MacOS 26

### ISSUE THREAD

**Issue by GideonBear** [h4llow3En/mac-notification-sys#79]
With `mac-notification-sys 0.6.8` on aarch64/arm64 MacOS 26:
```console
$ cargo install topgrade@16.1.2 --force
<SNIP>
error: linking with `cc` failed: exit status: 1
  |
  = note:  "cc" "<1 object files omitted>" "/var/folders/31/4zkfm2312m76_lvy86j94rsh0000gn/T/rustcCAlaFm/libmac_notification_sys-f40777ab68885596.rlib" "<sysroot>/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-*.rlib" "-framework" "CoreFoundation" "-framework" "Foundation" "-lSystem" "-framework" "CoreFoundation" "-lobjc" "-framework" "IOKit" "-framework" "IOKit" "-framework" "CoreFoundation" "-lobjc" "-framework" "Foundation" "-liconv" "-lSystem" "-lc" "-lm" "-arch" "arm64" "-mmacosx-version-min=11.0.0" "-L" "/var/folders/31/4zkfm2312m76_lvy86j94rsh0000gn/T/cargo-installv819of/release/build/mac-notification-sys-2ca20317557d5459/out" "-o" "/var/folders/31/4zkfm2312m76_lvy86j94rsh0000gn/T/cargo-installv819of/release/deps/topgrade-1241d411aa772f86" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: ld: warning: ignoring duplicate libraries: '-lSystem', '-lobjc'
          Undefined symbols for architecture arm64:
            "_LSCopyApplicationURLsForBundleIdentifier", referenced from:
                _setApplication in libmac_notification_sys-f40777ab68885596.rlib[2](54532c69c7c8f551-notify.o)
            "_OBJC_CLASS_$_NSImage", referenced from:
                 in libmac_notification_sys-f40777ab68885596.rlib[2](54532c69c7c8f551-notify.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
`mac-notification-sys 0.6.2` has no problems.
Posting on behalf of @lawlietl4 (https://github.com/topgrade-rs/topgrade/issues/1425), as I do not have any Apple hardware, [nor can I reproduce it in MacOS 15 CI](https://github.com/topgrade-rs/topgrade/pull/1429). I'm sure they can figure out a `git bisect` if no-one else can reproduce it though ;)

System info:
```console
$ cc --version
Apple clang version 17.0.0 (clang-1700.3.19.1)
Target: arm64-apple-darwin25.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
$ sw_vers -productVersion
26.0.1
```

**Comment by lawlietl4** [comment]
That's so weird because I look at the releases in this repo and 0.6.6 is the latest released here, did the dev push 0.6.8 to cargo and not to git?

**Comment by GideonBear** [comment]
> Also this error occured on other *NIX systems, my Ubuntu servers failed to upgrade too because of this with a similar error

Can you post the error? It is impossible for this to be the same error, as this library `mac-notification-sys` is specific to MacOS.

**Comment by AThePeanut4** [comment]
Oh this is just https://github.com/h4llow3En/mac-notification-sys/pull/78#issuecomment-3462736940

So we just need a new release with c30a9a27887ef7c11049c53fddc5194491ffac31 included :)

**Comment by AThePeanut4** [comment]
Running `cargo install --path .` in the topgrade repo works, but `cargo install topgrade@16.5.0` does not. I'm pretty sure this is because crates.io [does not allow dependencies on code published outside of crates.io](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-other-registries) (i.e. git).

So the only real solution is for a new release to be published to crates.io...

**Comment by hoodie** [comment]
alrighty, seems that we can savely close this then. Thanks everybody for checking in.

**Comment by GideonBear** [comment]
> alrighty, seems that we can savely close this then. Thanks everybody for checking in.

@hoodie
Sorry, I think you misunderstood; there's an issue here. The issue that was not here I was talking about, was about something else (failing on the main branch). The actual issue is fixed on the main branch, but we still need a new release on crates.io.

**Comment by hoodie** [comment]
sorry for the misunderstanding, I was totally convinced I had published it back then. please have a look at [`v0.6.9`](https://crates.io/crates/mac-notification-sys/0.6.9)
